on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Get pr info
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: info
      - name: Print info
        run: |
          echo "Has PR: ${steps.info.outputs.has-pr}"
          echo "PR: ${steps.info.outputs.pr-number}"
          echo "Contributor name: ${steps.info.outputs.contributor-name}"
          echo "Contributor username: ${steps.info.outputs.contributor-username}"
          echo "Repository name: ${steps.info.outputs.repository-name}"
